### ISSUE TITLE
Can you add this school?

### ISSUE THREAD

**Issue by ghost** [Gh0stByte/Blackboard-AutoLogin-iOS--HVCC-#1]
![img_1340](https://user-images.githubusercontent.com/28065292/35127290-4b47ea18-fc66-11e7-81e7-d7ad8316b5ed.PNG)

**Comment by Gh0stByte** [comment]
What exactly do you want to happen? Automatically login with the saved credentials? So you don't have to press the button? There doesn't seem to be a web component for this school.

**Comment by Gh0stByte** [comment]
Support for non-web logins added. Submitted to TheBigBoss
